<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="profile" nsURI="http://edu.uoc.som/openapi/profile/2.0" nsPrefix="openapi_profile">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="OpenAPIProfile"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="API">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" ordered="false"
        upperBound="-1" eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemeType">
    <eLiterals name="http"/>
    <eLiterals name="https" value="1"/>
    <eLiterals name="ws" value="2"/>
    <eLiterals name="wss" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxProperties" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minProperties" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalPropertiesAllowed"
        ordered="false" eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalProperties" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="APIOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" ordered="false"
        eType="#//HTTPMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="produces" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumes" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemes" ordered="false"
        upperBound="-1" eType="#//SchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" ordered="false" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" ordered="false"
        eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HTTPMethod">
    <eLiterals name="undefined"/>
    <eLiterals name="get" value="1"/>
    <eLiterals name="post" value="2"/>
    <eLiterals name="put" value="3"/>
    <eLiterals name="patch" value="4"/>
    <eLiterals name="options" value="5"/>
    <eLiterals name="delete" value="6"/>
    <eLiterals name="head" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIParameter" eSuperTypes="#//JSONSchemaSubset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        lowerBound="1" eType="#//ParameterLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowEmptyValue" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionFormat" ordered="false"
        eType="#//CollectionFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Parameter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false"
        eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JSONSchemaSubset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" ordered="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMaximum" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" ordered="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMinimum" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueItems" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleOf" ordered="false"
        eType="#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="java.lang.Double">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Real"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterLocation">
    <eLiterals name="undefined"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
    <eLiterals name="path" value="3"/>
    <eLiterals name="formData" value="4"/>
    <eLiterals name="body" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionFormat">
    <eLiterals name="undefined"/>
    <eLiterals name="csv" value="1"/>
    <eLiterals name="ssv" value="2"/>
    <eLiterals name="tsv" value="3"/>
    <eLiterals name="pipes" value="4"/>
    <eLiterals name="multi" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIResponse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" ordered="false"
        upperBound="-1" eType="#//Header" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" ordered="false"
        upperBound="-1" eType="#//Example" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Parameter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" ordered="false"
        eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//JSONDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionFormat" ordered="false"
        eType="#//CollectionFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minItems" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMinimum" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" ordered="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" ordered="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" ordered="false"
        eType="#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusiveMaximum" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueItems" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleOf" ordered="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum" ordered="false" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JSONDataType">
    <eLiterals name="undefined"/>
    <eLiterals name="boolean" value="1"/>
    <eLiterals name="integer" value="2"/>
    <eLiterals name="number" value="3"/>
    <eLiterals name="string" value="4"/>
    <eLiterals name="file" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Example">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="termsOfService" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" ordered="false"
        eType="#//License" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" ordered="false"
        eType="#//Contact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="License">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDocs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityDefinitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitySchemes" ordered="false"
        upperBound="-1" eType="#//SecurityScheme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityScheme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" eType="#//SecuritySchemeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        eType="#//APIKeyLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" ordered="false" eType="#//OAuth2FlowType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorizationURL" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenURL" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopes" ordered="false"
        upperBound="-1" eType="#//SecurityScope" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SecuritySchemeType">
    <eLiterals name="undefined"/>
    <eLiterals name="basic" value="1"/>
    <eLiterals name="apiKey" value="2"/>
    <eLiterals name="oauth2" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="APIKeyLocation">
    <eLiterals name="undefined"/>
    <eLiterals name="query" value="1"/>
    <eLiterals name="header" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OAuth2FlowType">
    <eLiterals name="undefined"/>
    <eLiterals name="implicit" value="1"/>
    <eLiterals name="password" value="2"/>
    <eLiterals name="application" value="3"/>
    <eLiterals name="accessCode" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityScope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Security">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityRequirements" ordered="false"
        upperBound="-1" eType="#//SecurityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitySchemes" ordered="false"
        upperBound="-1" eType="#//RequiredSecurityScheme" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredSecurityScheme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopes" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tags">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" ordered="false" lowerBound="1"
        upperBound="-1" eType="#//Tag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalDocsURL" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalDocsDescription"
        ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrapped" ordered="false"
        eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//JSONDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Enumeration" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Enumeration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_PrimitiveType" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIProperty" eSuperTypes="#//JSONSchemaSubset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false"
        eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xml" ordered="false" eType="#//XMLElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isID" ordered="false" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includesTarget" ordered="false"
        lowerBound="1" eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
</ecore:EPackage>
